### ISSUE TITLE
everyone to be able to setup GPU instance

### ISSUE THREAD

**Issue by taeil** [Berkeley-Data/irrigation_detection#16]
1. find setup instructions
2. start GPU instance 
3. build docker 
4. run notebook (any) 
5. confirm tensorflow and panda version 

done. 

- [x] @suryatechie 
- [x] @TsungChinHanKen 
- [x] @oropezaev 
- [x] @taeil

**Comment by TsungChinHanKen** [comment]
I setup it already but cannot open jupyter notebook thru http://127.0.0.1:8888 in browser. any suggestion for my setting to be wrong?

**Comment by TsungChinHanKen** [comment]
Thanks. Resolved.
