### ISSUE TITLE
preprocess BigEarthNet data converting to TFRecords 

### ISSUE THREAD

**Issue by taeil** [Berkeley-Data/irrigation_detection#17]
1. adjust docker accordingly to run preprocess_tfrecords*.py 
2. merge preprocess_tfrecords scripts into single make_dataset.py 
3. include downloading BE data and extraction
```
# download 66GB package 
curl http://bigearth.net/downloads/BigEarthNet-S2-v1.0.tar.gz -o data/raw/BigEarthNet-v1.0.zip

# extract 
tar -xvf data/raw/BigEarthNet-v1.0.tar.gz data/raw
```
running make_dataset.py should prepare whole datasets end to end.

**Comment by suryatechie** [comment]
I started working on it. Hopefully, it should be done today unless there are some surprises!

**Comment by taeil** [comment]
TFRecords has been generated (train, val, test). 
TFRecords with irrigation and non-irrigation has been generated. 
Sharding is in process and will upload to s3 shortly. 

also, we have new single script (make_datasets.py)

**Comment by taeil** [comment]
1. download (aws s3 sync) from s3 bucket. script for s3 download @taeil  
2. everyone to download them. 
no mount! 

- [ ] @oropezaev when download is done 
- [ ] @taeil when script is done 
- [ ] @TsungChinHanKen  when download is done 
- [ ] @suryatechie  when you are done uploading to s3
